CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE amonet_sprint (
    id_amonet_sprint UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    contador INTEGER GENERATED BY DEFAULT AS IDENTITY,
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    principal BOOLEAN NOT NULL,
    descripcion TEXT NULL,
    usuario_alta UUID NOT NULL,
    usuario_modifica UUID NULL,
    fecha_modifica TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uq_sprint_principal ON amonet_sprint(principal) WHERE principal = TRUE;
